# Generated by Django 5.2.6 on 2025-09-10 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_documentanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('scenario', models.CharField(choices=[('normal', 'Normal'), ('missed_payment', 'Missed Payment'), ('early_termination', 'Early Termination')], default='normal', max_length=32)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('jurisdiction', models.CharField(blank=True, default='', max_length=128)),
                ('jurisdiction_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='api.parseddocument')),
            ],
        ),
        migrations.CreateModel(
            name='SimulationRiskAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('high', 'High'), ('critical', 'Critical')], default='info', max_length=16)),
                ('message', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_alerts', to='api.simulationsession')),
            ],
        ),
        migrations.CreateModel(
            name='SimulationPenaltyForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fees_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('penalties_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalty_forecast', to='api.simulationsession')),
            ],
        ),
        migrations.CreateModel(
            name='SimulationNarrativeOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('narrative', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=16)),
                ('key_points', models.JSONField(blank=True, default=list)),
                ('financial_impact', models.JSONField(blank=True, default=list)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narratives', to='api.simulationsession')),
            ],
        ),
        migrations.CreateModel(
            name='SimulationLongTermPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(blank=True, default='', max_length=64)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='long_term', to='api.simulationsession')),
            ],
            options={
                'ordering': ['index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SimulationExitComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('penalty_text', models.CharField(blank=True, default='', max_length=64)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=16)),
                ('benefits_lost', models.CharField(blank=True, default='', max_length=128)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_comparisons', to='api.simulationsession')),
            ],
        ),
        migrations.CreateModel(
            name='SimulationTimelineNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=512)),
                ('detailed_description', models.TextField(blank=True, default='')),
                ('risks', models.JSONField(blank=True, default=list)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='api.simulationsession')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
