# Generated by Django 5.2.5 on 2025-09-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_simulationsession_simulationriskalert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationlongtermpoint',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
