# Generated by Django 5.2.5 on 2025-09-17 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_documenttranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAnalysisTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ta', 'Tamil'), ('te', 'Telugu')], max_length=2)),
                ('translated_analysis_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='api.documentanalysis')),
            ],
            options={
                'unique_together': {('analysis', 'language')},
            },
        ),
    ]
