# Generated by Django 5.2.5 on 2025-09-18 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_documentanalysistranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationExitComparisonTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ta', 'Tamil'), ('te', 'Telugu')], max_length=2)),
                ('translated_label', models.CharField(max_length=128)),
                ('translated_penalty_text', models.CharField(blank=True, default='', max_length=64)),
                ('translated_benefits_lost', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='api.simulationexitcomparison')),
            ],
            options={
                'unique_together': {('comparison', 'language')},
            },
        ),
        migrations.CreateModel(
            name='SimulationLongTermPointTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ta', 'Tamil'), ('te', 'Telugu')], max_length=2)),
                ('translated_label', models.CharField(blank=True, default='', max_length=64)),
                ('translated_description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='api.simulationlongtermpoint')),
            ],
            options={
                'unique_together': {('point', 'language')},
            },
        ),
        migrations.CreateModel(
            name='SimulationNarrativeOutcomeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ta', 'Tamil'), ('te', 'Telugu')], max_length=2)),
                ('translated_title', models.CharField(max_length=255)),
                ('translated_subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('translated_narrative', models.TextField()),
                ('translated_key_points', models.JSONField(blank=True, default=list)),
                ('translated_financial_impact', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='api.simulationnarrativeoutcome')),
            ],
            options={
                'unique_together': {('outcome', 'language')},
            },
        ),
        migrations.CreateModel(
            name='SimulationPenaltyForecastTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ta', 'Tamil'), ('te', 'Telugu')], max_length=2)),
                ('translated_label', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='api.simulationpenaltyforecast')),
            ],
            options={
                'unique_together': {('forecast', 'language')},
            },
        ),
        migrations.CreateModel(
            name='SimulationRiskAlertTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ta', 'Tamil'), ('te', 'Telugu')], max_length=2)),
                ('translated_message', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='api.simulationriskalert')),
            ],
            options={
                'unique_together': {('alert', 'language')},
            },
        ),
        migrations.CreateModel(
            name='SimulationSessionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ta', 'Tamil'), ('te', 'Telugu')], max_length=2)),
                ('translated_title', models.CharField(blank=True, default='', max_length=255)),
                ('translated_jurisdiction', models.CharField(blank=True, default='', max_length=128)),
                ('translated_jurisdiction_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='api.simulationsession')),
            ],
            options={
                'unique_together': {('session', 'language')},
            },
        ),
        migrations.CreateModel(
            name='SimulationTimelineNodeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ta', 'Tamil'), ('te', 'Telugu')], max_length=2)),
                ('translated_title', models.CharField(max_length=255)),
                ('translated_description', models.CharField(blank=True, default='', max_length=512)),
                ('translated_detailed_description', models.TextField(blank=True, default='')),
                ('translated_risks', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='api.simulationtimelinenode')),
            ],
            options={
                'unique_together': {('node', 'language')},
            },
        ),
    ]
